Repository Team15MyMedia/MyMedia, pull requests merged in 2023-10, with the labels that each got.

#40 -[기능 추가] : 썸네일 화질 변경
  app/src/main/java/com/example/mymedia/detail/DetailActivity.kt
  app/src/main/java/com/example/mymedia/home/HomeFragment.kt
  app/src/main/java/com/example/mymedia/home/HomeViewModel.kt
  app/src/main/java/com/example/mymedia/home/ThumbnailQuality.kt
  app/src/main/java/com/example/mymedia/home/adapter/HomeCategoryVideoListAdapter.kt
  app/src/main/res/layout/activity_detail.xml
Labels: feature

#42 -[기능 추가] : short 동영상 제외 기능 추가
  app/src/main/java/com/example/mymedia/data/ApiResponse.kt
  app/src/main/java/com/example/mymedia/data/ItemRepository.kt
  app/src/main/java/com/example/mymedia/data/RetrofitApi.kt
Labels: feature

#46 - [버그 수정] : DetailPage에서 돌아올 시 스피너 값 초기화 문제 해결
  app/src/main/java/com/example/mymedia/home/HomeFragment.kt
  app/src/main/java/com/example/mymedia/home/HomeViewModel.kt
Labels: bug

#47 -[구조 수정] : ListAdapter 변경
  app/src/main/java/com/example/mymedia/data/ItemRepository.kt
  app/src/main/java/com/example/mymedia/data/RetrofitInstance.kt
  app/src/main/java/com/example/mymedia/search/SearchFragmentPopular.kt
  app/src/main/java/com/example/mymedia/search/SearchFragmentResult.kt
  app/src/main/java/com/example/mymedia/search/SearchRVAdapter.kt
  app/src/main/java/com/example/mymedia/search/SearchResultChannelRVAdapter.kt
  app/src/main/java/com/example/mymedia/search/SearchResultVideoRVAdapter.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/rv_videos_item.xml
Labels: fix

#49 - [버그 수정] : CategoryList 수정
  app/src/main/java/com/example/mymedia/data/ApiResponse.kt
  app/src/main/java/com/example/mymedia/data/ItemRepository.kt
Labels: bug, fix

#54 -[기능 추가] : home 무한 스크롤 구현
  app/src/main/java/com/example/mymedia/data/ItemRepository.kt
  app/src/main/java/com/example/mymedia/data/RetrofitApi.kt
  app/src/main/java/com/example/mymedia/home/HomeFragment.kt
  app/src/main/java/com/example/mymedia/home/HomeViewModel.kt
  app/src/main/res/layout/fragment_home.xml
Labels: feature, fix

#55 - [기능 추가] : Search Page 오류 예외 처리
  app/src/main/java/com/example/mymedia/data/ItemRepository.kt
  app/src/main/java/com/example/mymedia/main/MainActivity.kt
  app/src/main/java/com/example/mymedia/search/SearchFragment.kt
  app/src/main/java/com/example/mymedia/search/SearchFragmentPopular.kt
  app/src/main/java/com/example/mymedia/search/SearchFragmentResult.kt
  app/src/main/java/com/example/mymedia/search/SearchViewModel.kt
Labels: feature

#58 -[버그 수정] : 오류 예외 처리 수정
  app/src/main/java/com/example/mymedia/search/SearchViewModel.kt
Labels: bug, fix

#59 - [기능 추가] : api 절약모드 추가
  app/src/main/java/com/example/mymedia/data/Data.kt
  app/src/main/java/com/example/mymedia/home/HomeViewModel.kt
  app/src/main/java/com/example/mymedia/search/SearchViewModel.kt
Labels: feature

#66 - [버그 수정] : most popluar video 수정
  app/src/main/java/com/example/mymedia/data/ItemRepository.kt
  app/src/main/java/com/example/mymedia/data/RetrofitApi.kt
  app/src/main/java/com/example/mymedia/home/HomeFragment.kt
  app/src/main/java/com/example/mymedia/home/adapter/HomeCategoryVideoListAdapter.kt
  app/src/main/java/com/example/mymedia/home/adapter/HomeMostViewListAdapter.kt
  app/src/main/java/com/example/mymedia/search/SearchFragmentPopular.kt
  app/src/main/java/com/example/mymedia/search/SearchFragmentResult.kt
  app/src/main/java/com/example/mymedia/search/SearchRVAdapter.kt
  app/src/main/java/com/example/mymedia/search/SearchResultVideoRVAdapter.kt
  app/src/main/java/com/example/mymedia/search/SearchViewModel.kt
Labels: bug, fix

#68 - [기능 추가] : home banner 세부 기능 추가
  app/src/main/java/com/example/mymedia/home/HomeFragment.kt
  app/src/main/java/com/example/mymedia/home/HomeViewModel.kt
Labels: feature

#70 -[디자인] : 썸네일 해상도 높이기
  app/src/main/java/com/example/mymedia/data/Data.kt
  app/src/main/java/com/example/mymedia/detail/DetailActivity.kt
  app/src/main/java/com/example/mymedia/home/HomeFragment.kt
  app/src/main/java/com/example/mymedia/home/HomeViewModel.kt
  app/src/main/java/com/example/mymedia/home/ThumbnailQuality.kt
  app/src/main/java/com/example/mymedia/home/adapter/HomeCategoryVideoListAdapter.kt
  app/src/main/java/com/example/mymedia/home/adapter/HomeMostViewListAdapter.kt
  app/src/main/java/com/example/mymedia/mypage/MyPageFavoriteListAdapter.kt
  app/src/main/java/com/example/mymedia/mypage/MyPageViewModel.kt
  app/src/main/java/com/example/mymedia/search/SearchRVAdapter.kt
  app/src/main/java/com/example/mymedia/search/SearchResultVideoRVAdapter.kt
  app/src/main/java/com/example/mymedia/search/SearchViewModel.kt
  app/src/main/res/anim/scale_down.xml
  app/src/main/res/values/styles.xml
Labels: design

#73 -[기능 추가] : 디테일 페이지에서 영상 재생 기능
  app/build.gradle
  app/src/main/java/com/example/mymedia/detail/DetailActivity.kt
  app/src/main/java/com/example/mymedia/search/SearchViewModel.kt
  app/src/main/res/anim/scale_down.xml
  app/src/main/res/layout/activity_detail.xml
Labels: feature

#75 - [기능 추가] : Detail 페이지에 isFavorite전달
  app/build.gradle
  app/src/main/java/com/example/mymedia/detail/DetailActivity.kt
  app/src/main/java/com/example/mymedia/home/HomeFragment.kt
  app/src/main/java/com/example/mymedia/home/HomeViewModel.kt
  app/src/main/java/com/example/mymedia/main/MainActivity.kt
  app/src/main/java/com/example/mymedia/main/MainSharedViewModel.kt
  app/src/main/java/com/example/mymedia/mypage/MyPageFragment.kt
  app/src/main/java/com/example/mymedia/provider/ContextProvider.kt
Labels: feature

#77 - [기능 추가] : 찜 리스트 구현 및 적용
  app/src/main/java/com/example/mymedia/detail/DetailActivity.kt
  app/src/main/java/com/example/mymedia/home/HomeFragment.kt
  app/src/main/java/com/example/mymedia/main/MainSharedViewModel.kt
  app/src/main/java/com/example/mymedia/mypage/MyPageFragment.kt
  app/src/main/java/com/example/mymedia/mypage/MyPageViewModel.kt
  app/src/main/res/drawable/ic_sel_like_bt.xml
Labels: feature

#81 - [기능 추가] : shared preference
  app/build.gradle
  app/src/main/java/com/example/mymedia/data/ItemRepository.kt
  app/src/main/java/com/example/mymedia/data/RetrofitApi.kt
  app/src/main/java/com/example/mymedia/home/HomeFragment.kt
  app/src/main/java/com/example/mymedia/main/ContextProvider.kt
  app/src/main/java/com/example/mymedia/main/MainSharedViewModel.kt
  app/src/main/java/com/example/mymedia/mypage/MyPageFragment.kt
  app/src/main/java/com/example/mymedia/mypage/MyPageViewModel.kt
  app/src/main/java/com/example/mymedia/search/SearchFragment.kt
  app/src/main/java/com/example/mymedia/search/SearchFragmentPopular.kt
  app/src/main/java/com/example/mymedia/search/SearchFragmentResult.kt
  app/src/main/java/com/example/mymedia/search/SearchResultChannelRVAdapter.kt
  app/src/main/java/com/example/mymedia/search/SearchResultVideoRVAdapter.kt
  app/src/main/java/com/example/mymedia/search/SearchViewModel.kt
  app/src/main/res/layout/rv_videos_item.xml
Labels: feature, fix

#82 - [버그 수정] : long click -> click
  app/src/main/java/com/example/mymedia/data/Data.kt
  app/src/main/java/com/example/mymedia/home/HomeViewModel.kt
  app/src/main/java/com/example/mymedia/mypage/MyPageFavoriteListAdapter.kt
  app/src/main/java/com/example/mymedia/mypage/MyPageFragment.kt
  app/src/main/java/com/example/mymedia/search/SearchViewModel.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_home.xml
Labels: fix

#83 - [버그 수정] : 검색 결과 없을 때 error
  app/src/main/java/com/example/mymedia/search/SearchViewModel.kt
Labels: bug, fix

#84 - [버그 수정] : myPage max 줄 수 지정
  app/src/main/res/layout/mypage_video_item.xml
Labels: design, fix

#85 -[구조 수정] : 스플래쉬 화면 클릭 없이 넘어가게 하기
  app/src/main/java/com/example/mymedia/SplashActivity.kt
  app/src/main/java/com/example/mymedia/home/HomeViewModel.kt
  app/src/main/res/xml/activity_splash_scene.xml
Labels: fix
