Repository Team15MyMedia/MyMedia, pull requests merged in 2023-09, with the labels that each got.

#3 Design detail page
  app/src/main/res/drawable/ic_back_bt.xml
  app/src/main/res/drawable/ic_face.xml
  app/src/main/res/drawable/ic_sel_home_bt.xml
  app/src/main/res/drawable/ic_sel_like_bt.xml
  app/src/main/res/drawable/ic_sel_mypage_bt.xml
  app/src/main/res/drawable/ic_sel_search_bt.xml
  app/src/main/res/drawable/ic_share_bt.xml
  app/src/main/res/drawable/ic_top10.xml
  app/src/main/res/drawable/ic_unsel_home_bt.xml
  app/src/main/res/drawable/ic_unsel_like_bt.xml
  app/src/main/res/drawable/ic_unsel_mypage_bt.xml
  app/src/main/res/drawable/ic_unsel_search_bt.xml
  app/src/main/res/layout/fragment_home.xml
  gradlew
Labels: design

#7 Design: Mypage 디자인
  app/src/main/res/drawable/home.png
  app/src/main/res/drawable/icon5.png
  app/src/main/res/drawable/movies.png
  app/src/main/res/drawable/mypage.png
  app/src/main/res/drawable/search.png
  app/src/main/res/layout/fragment_mypage.xml
Labels: design

#8 Design:detail page
  app/src/main/res/drawable/_2023_09_25_171503.png
  app/src/main/res/layout/fragment_detail.xml
Labels: design

#9 Feature: 홈 화면 기능 추가
  app/src/main/java/com/example/mymedia/home/HomeFragment.kt
  app/src/main/java/com/example/mymedia/home/HomeVideoListAdapter.kt
  app/src/main/java/com/example/mymedia/home/HomeViewModel.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/video_item.xml
  app/src/main/res/values/styles.xml
Labels: feature

#14 FEAT: 메인 화면 스와이프로 탭 이동 금지 기능 추가
  app/src/main/java/com/example/mymedia/main/MainActivity.kt
Labels: design, feature

#17 - [기능 추가] : home UI 구체화
  app/src/main/java/com/example/mymedia/home/HomeFragment.kt
  app/src/main/java/com/example/mymedia/home/HomeVideoListAdapter.kt
  app/src/main/java/com/example/mymedia/home/HomeViewModel.kt
  app/src/main/java/com/example/mymedia/home/adapter/HomeChannelListAdapter.kt
  app/src/main/java/com/example/mymedia/home/adapter/HomeVideoListAdapter.kt
  app/src/main/java/com/example/mymedia/main/MainActivity.kt
  app/src/main/java/com/example/mymedia/main/MainViewPagerAdapter.kt
  app/src/main/res/drawable/rounded_corner_bg.xml
  app/src/main/res/layout/channel_item.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/styles.xml
Labels: design, feature

#18 Design: 버튼 UI 구현
  app/src/main/res/drawable/background_color1.xml
  app/src/main/res/layout/fragment_mypage.xml
Labels: design

#19 -[기능 추가] : 탭 레이아웃
  app/build.gradle
  app/src/main/java/com/example/mymedia/main/MainActivity.kt
  app/src/main/res/drawable/bx_bxs_share_alt.png
  app/src/main/res/drawable/group.png
  app/src/main/res/drawable/group_1.png
  app/src/main/res/drawable/group_2.png
  app/src/main/res/drawable/group_3.png
  app/src/main/res/drawable/group_4.png
  app/src/main/res/drawable/group_48.png
  app/src/main/res/drawable/group_48_1.png
  app/src/main/res/drawable/group_49.png
  app/src/main/res/drawable/group_50.png
  app/src/main/res/drawable/group_51.png
  app/src/main/res/drawable/ic_sel_home_bt.xml
  app/src/main/res/drawable/rectangle_5.png
Labels: feature

#21 [구조 수정] : itemModel 수정
  app/src/main/java/com/example/mymedia/data/Data.kt
  app/src/main/java/com/example/mymedia/data/ItemModel.kt
  app/src/main/java/com/example/mymedia/home/HomeFragment.kt
  app/src/main/java/com/example/mymedia/home/HomeViewModel.kt
  app/src/main/java/com/example/mymedia/home/adapter/HomeChannelListAdapter.kt
  app/src/main/java/com/example/mymedia/home/adapter/HomeVideoListAdapter.kt
  app/src/main/java/com/example/mymedia/search/SearchRVAdapter.kt
  app/src/main/java/com/example/mymedia/search/SearchResultRVAdapter.kt
Labels: feature

#22 -[기능 추가] : 탭 레이아웃
  app/src/main/java/com/example/mymedia/main/MainActivity.kt
  app/src/main/res/drawable/bx_bxs_share_alt.png
  app/src/main/res/drawable/group.png
  app/src/main/res/drawable/group_1.png
  app/src/main/res/drawable/group_2.png
  app/src/main/res/drawable/group_3.png
  app/src/main/res/drawable/group_4.png
  app/src/main/res/drawable/group_48.png
  app/src/main/res/drawable/group_48_1.png
  app/src/main/res/drawable/group_49.png
  app/src/main/res/drawable/group_50.png
  app/src/main/res/drawable/group_51.png
  app/src/main/res/drawable/rectangle_5.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: feature

#27 - [기능 추가] : home UI Channel 기능 구현
  app/src/main/java/com/example/mymedia/data/Data.kt
  app/src/main/java/com/example/mymedia/data/ItemModel.kt
  app/src/main/java/com/example/mymedia/data/ItemRepository.kt
  app/src/main/java/com/example/mymedia/data/RetrofitApi.kt
  app/src/main/java/com/example/mymedia/home/HomeFragment.kt
  app/src/main/java/com/example/mymedia/home/HomeViewModel.kt
  app/src/main/java/com/example/mymedia/home/adapter/HomeCategoryVideoListAdapter.kt
  app/src/main/java/com/example/mymedia/home/adapter/HomeChannelListAdapter.kt
Labels: feature

#30 [기능 추가] : SearchPage Video 데이터 연결
  app/src/main/java/com/example/mymedia/data/ItemRepository.kt
  app/src/main/java/com/example/mymedia/data/RetrofitApi.kt
  app/src/main/java/com/example/mymedia/search/SearchFragment.kt
  app/src/main/java/com/example/mymedia/search/SearchFragmentPopular.kt
  app/src/main/java/com/example/mymedia/search/SearchFragmentResult.kt
  app/src/main/java/com/example/mymedia/search/SearchRVAdapter.kt
  app/src/main/java/com/example/mymedia/search/SearchResultRVAdapter.kt
  app/src/main/java/com/example/mymedia/search/SearchViewModel.kt
Labels: feature

#31 - [기능 추가] : home UI Category 기능 구현
  app/src/main/java/com/example/mymedia/data/ApiResponse.kt
  app/src/main/java/com/example/mymedia/data/ItemModel.kt
  app/src/main/java/com/example/mymedia/data/ItemRepository.kt
  app/src/main/java/com/example/mymedia/data/RetrofitApi.kt
  app/src/main/java/com/example/mymedia/home/HomeFragment.kt
  app/src/main/java/com/example/mymedia/home/HomeViewModel.kt
Labels: feature

#32 -[기능 추가] : 디테일 페이지 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mymedia/detail/DetailActivity.kt
  app/src/main/java/com/example/mymedia/detail/DetailFragment.kt
  app/src/main/java/com/example/mymedia/home/HomeFragment.kt
  app/src/main/java/com/example/mymedia/home/HomeViewModel.kt
  app/src/main/java/com/example/mymedia/main/MainActivity.kt
  app/src/main/res/layout/activity_detail.xml
Labels: feature

#34 - [기능 추가] : home UI Category에 따른 Channel 로드 기능 구현
  app/src/main/java/com/example/mymedia/data/ApiResponse.kt
  app/src/main/java/com/example/mymedia/data/Data.kt
  app/src/main/java/com/example/mymedia/data/ItemModel.kt
  app/src/main/java/com/example/mymedia/data/ItemRepository.kt
  app/src/main/java/com/example/mymedia/data/RetrofitApi.kt
  app/src/main/java/com/example/mymedia/home/HomeFragment.kt
  app/src/main/java/com/example/mymedia/home/HomeViewModel.kt
  app/src/main/java/com/example/mymedia/search/SearchViewModel.kt
Labels: feature

#36 -[기능 추가] : SearchPage Category 데이터 연결
  app/src/main/java/com/example/mymedia/data/RetrofitApi.kt
  app/src/main/java/com/example/mymedia/search/SearchFragment.kt
  app/src/main/java/com/example/mymedia/search/SearchFragmentPopular.kt
  app/src/main/java/com/example/mymedia/search/SearchFragmentResult.kt
  app/src/main/java/com/example/mymedia/search/SearchResultChannelRVAdapter.kt
  app/src/main/java/com/example/mymedia/search/SearchResultRVAdapter.kt
  app/src/main/java/com/example/mymedia/search/SearchResultVideoRVAdapter.kt
  app/src/main/java/com/example/mymedia/search/SearchViewModel.kt
Labels: feature

#38 - [리드미] : 리드미 초안 작성
  README.md
Labels: documentation

#39 - [디자인/기능 추가] : MyPage 디자인 구현 및 일부 기능 구현
  .DS_Store
  .gitignore
  app/src/main/java/com/example/mymedia/data/Data.kt
  app/src/main/java/com/example/mymedia/home/HomeFragment.kt
  app/src/main/java/com/example/mymedia/mypage/MyPageFavoriteListAdapter.kt
  app/src/main/java/com/example/mymedia/mypage/MyPageFragment.kt
  app/src/main/java/com/example/mymedia/mypage/MyPageViewModel.kt
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/mypage_video_item.xml
Labels: design, feature
